### ISSUE TITLE
Не получається добавити лічильник газу до інформаційної панелі

### ISSUE THREAD

**Issue by amgstone** [vit-um/hass#1]
Не получається добавити лічильник газу до інформаційної панелі, все зробив по інструкції, але не візуалізується utility meter газу в інформаційній панелі.

**Comment by vit-um** [comment]
Додав в розділ інструкції [Підготовка сенсорів](https://github.com/vit-um/hass/wiki/6.-Configure-Home-Assistant-Energy-Dashboard#%D0%BF%D1%96%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0-%D1%81%D0%B5%D0%BD%D1%81%D0%BE%D1%80%D1%96%D0%B2) пункти з 6 по 9. Спробуйте повторити ці дії. Якщо я не вгадав Вашу проблему, то прошу описати її більш детально.
